#!/usr/bin/env python3
"""Join the triage measurements to a hand-maintained file/book mapping.

Two files, two lifetimes:

  pipeline/triage.csv   disposable. Regenerated whenever triage.py runs, and
                        overwritten without ceremony.
  pipeline/mapping.csv  durable. The hand-maintained record of which file is
                        which book. Survives re-measurement, and is the thing
                        every citation and every note anchor depends on.

mapping.csv matches on a distinctive substring rather than a full filename,
because these filenames run to 200 characters and change when someone renames a
download. A match must identify exactly one book; a book may have several files.

    python3 pipeline/link.py

Writes db/link-sources.sql for review. SQL rather than a direct write, so the
mapping can be read before it runs.
"""

import csv
import sys
import unicodedata
from collections import defaultdict
from pathlib import Path

PIPELINE = Path(__file__).parent
TRIAGE = PIPELINE / "triage.csv"
MAPPING = PIPELINE / "mapping.csv"
OUT = PIPELINE.parent / "db" / "link-sources.sql"

# triage classification -> books.source_format
FORMAT = {
    "pdf_text": "pdf_text",
    "pdf_ocr_needed": "pdf_ocr",   # true once OCR has actually run
    "mixed": "pdf_ocr",
}


def quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


# macOS stores filenames in decomposed Unicode (NFD): "á" is "a" plus a
# combining acute. A rule typed in a text editor is composed (NFC). The two are
# different byte sequences, so a plain substring test silently fails on every
# accented title — which is most of this corpus.
#
# Folding accents away entirely, rather than merely normalising, also means a
# rule can be typed as "Catalogo" and still match "Catálogo". The same trade the
# chunk loader makes for chunks.text_search: papa and papá collide, and that is
# fine for matching filenames.
def fold(value: str) -> str:
    decomposed = unicodedata.normalize("NFKD", value)
    stripped = "".join(c for c in decomposed if not unicodedata.combining(c))
    return stripped.casefold()


def main() -> None:
    for path in (TRIAGE, MAPPING):
        if not path.exists():
            sys.exit(f"{path} not found.")

    with TRIAGE.open(encoding="utf-8") as handle:
        files = list(csv.DictReader(handle))

    with MAPPING.open(encoding="utf-8") as handle:
        rules = [r for r in csv.DictReader(handle) if r["match"].strip()]

    matched: dict[str, list[dict]] = defaultdict(list)
    unmatched = []
    ambiguous = []

    for row in files:
        name = fold(row["filename"])
        hits = [r for r in rules if fold(r["match"].strip()) in name]

        if not hits:
            unmatched.append(row["filename"])
            continue
        if len(hits) > 1:
            ambiguous.append((row["filename"], [h["match"] for h in hits]))
            continue

        matched[hits[0]["book_id"].strip()].append({**row, "note": hits[0]["note"]})

    if ambiguous:
        print("Ambiguous — one file matched several rules. Fix mapping.csv:\n")
        for name, rule_matches in ambiguous:
            print(f"  {name[:70]}")
            for m in rule_matches:
                print(f"      matched by: {m}")
        sys.exit(1)

    statements = []
    multi = []

    for book_id, entries in sorted(matched.items()):
        entries.sort(key=lambda e: e["filename"])
        primary = entries[0]

        if len(entries) > 1:
            multi.append((book_id, [e["filename"] for e in entries]))

        fmt = FORMAT.get(primary["classification"], "none")

        # Provisional handling of several files per book: the first goes in
        # source_path, the rest are recorded in notes_internal, so nothing is
        # lost while ARCHITECTURE.md open item 1 is undecided.
        notes = [e["note"] for e in entries if e.get("note")]
        if len(entries) > 1:
            notes.append(
                "Several files for this title: " + "; ".join(e["filename"] for e in entries)
            )

        parts = [
            "update books set",
            f"  source_format = {quote(fmt)},",
            f"  source_path   = {quote('pipeline/corpus/' + primary['filename'])},",
        ]
        if notes:
            joined = " | ".join(notes)
            parts.append(
                f"  notes_internal = coalesce(notes_internal || ' | ', '') || {quote(joined)},"
            )
        parts.append("  updated_at    = now()")
        parts.append(f"where id = {quote(book_id)};")

        statements.append("\n".join(parts) + "\n")

    header = [
        "-- Scriptorium — link source files to catalogue records",
        "--",
        "-- Generated by pipeline/link.py from triage.csv and mapping.csv.",
        "-- Re-runnable. Review before running: this mapping is what every",
        "-- citation and every note anchor depends on.",
        "--",
        f"-- {sum(len(v) for v in matched.values())} files mapped to {len(matched)} books.",
        "",
        "begin;",
        "",
    ]

    OUT.write_text("\n".join(header) + "\n".join(statements) + "\ncommit;\n", encoding="utf-8")

    print(f"Wrote {OUT}")
    print(f"  {sum(len(v) for v in matched.values())} files -> {len(matched)} books")

    if multi:
        print(f"\n  {len(multi)} books have more than one file:")
        for book_id, names in multi:
            print(f"    {book_id}")
            for name in names:
                print(f"      {name[:70]}")

    if unmatched:
        print(f"\n  {len(unmatched)} files match no rule — not on the reading list,")
        print("  or waiting on a decision:")
        for name in unmatched:
            print(f"    {name[:78]}")


if __name__ == "__main__":
    main()
