// The quotation matcher: normalize, key and Book.find from pipeline/dossier.py,
// ported to behave identically. It is what guarantees that no quotation is
// invented: a quotation is stored only if it is found in the book's own page
// text, and what is stored is the book's text at the match and the printed
// page where it was found (docs/PAGE-NUMBERS.md for how that page is derived).
//
// THE PYTHON IS THE SPECIFICATION. tests/matcher/ holds the fixtures both
// sides must pass: cases.json (hand-written inputs), expected.json (what
// dossier.py returns for them, generated by pipeline/matcher_fixtures.py),
// and corpus.json (real pages from Neon, gitignored). A change to either side
// regenerates expected.json and passes both runners:
//
//     pipeline/.venv/bin/python3 pipeline/test_matcher.py
//     npm run test:matcher
//
// This is deliberately not lib/quotation.ts's normalizeQuotation, which the
// note form uses: that has no NFC step and takes letters as \p{L}. Matching
// both sides with this function is what makes the comparison fair whatever
// produced the quotation.
//
// WHERE JAVASCRIPT AND PYTHON DIFFER, and what is done about it:
//
//   whitespace   Python's \s and str.strip() accept U+001C-U+001F and U+0085
//                and not U+FEFF; JavaScript's \s and trim() the reverse. SPACE
//                below is Python's set, written out.
//   letters      Python's [^\W\d_] is alphabetic characters plus numeric
//                characters that are not decimal digits (½, Roman numerals).
//                LETTER below is \p{L}, \p{Nl}, \p{No}.
//   lengths      Python counts characters (code points), JavaScript's .length
//                counts UTF-16 code units. The close match and every length
//                test count code points. The exact match slices by code units,
//                which is the same thing as long as key() leaves every page's
//                code-unit length unchanged; keyOf() checks that and throws.
//   rounding     Python's '.0%' rounds half to even; percent() does the same.

import { matchingBlocks } from './sequence-matcher';

export const MIN_QUOTE_CHARS = 25; // shorter than this matches too easily to prove anything
export const FIRST_CITABLE_PAGE = 1; // below this is front matter
export const FUZZY_RATIO = 0.92; // share of the quotation's characters that must align

const SPACE =
  '\\t\\n\\u000B\\f\\r\\u001C-\\u001F \\u0085\\u00A0\\u1680\\u2000-\\u200A' +
  '\\u2028\\u2029\\u202F\\u205F\\u3000';
const LETTER = '\\p{L}\\p{Nl}\\p{No}';

const SOFT_HYPHEN = /\u00AD/g;
const NOTE_REFERENCE = /[\u2070\u00B9\u00B2\u00B3\u2074-\u2079]+/g;
const HYPHEN_AT_LINE_END = new RegExp(
  `([${LETTER}])[-\\u2010\\u2011][${SPACE}]*\\n[${SPACE}]*([${LETTER}])`,
  'gu',
);
const LINE_BREAK = new RegExp(`[${SPACE}]*\\n[${SPACE}]*`, 'gu');
const RUN_OF_SPACES = /[ \t\u00A0]+/g;
const EDGE_SPACE = new RegExp(`^[${SPACE}]+|[${SPACE}]+$`, 'gu');
const ENDS_IN_BROKEN_WORD = new RegExp(`[${LETTER}][-\\u2010\\u2011]$`, 'u');
const STARTS_WITH_LETTER = new RegExp(`^[${LETTER}]`, 'u');

// Stripped from both ends of a quotation before it is looked up.
const QUOTE_MARKS = new Set([' ', '"', "'", '\u201C', '\u201D', '\u00AB', '\u00BB']);

// One character for one character, so a position in the key is a position in
// the normalized text and the book's own span can be cut from it.
const KEY_MAP: Record<string, string> = {
  '\u201C': '"', '\u201D': '"', '\u201E': '"', '\u00AB': '"', '\u00BB': '"',
  '\u2018': "'", '\u2019': "'", '\u201A': "'", '\u2039': "'", '\u203A': "'",
  '\u2013': '-', '\u2014': '-', '\u2010': '-', '\u2011': '-',
};

function codePoints(s: string): number {
  let n = 0;
  for (const _ of s) n += 1;
  return n;
}

// str.strip() with no argument.
function pyStrip(s: string): string {
  return s.replace(EDGE_SPACE, '');
}

// str.strip(chars).
function stripChars(s: string, chars: Set<string>): string {
  const cs = Array.from(s);
  let start = 0;
  let end = cs.length;
  while (start < end && chars.has(cs[start])) start += 1;
  while (end > start && chars.has(cs[end - 1])) end -= 1;
  return cs.slice(start, end).join('');
}

// f"{ratio:.0%}": the ratio times 100, rounded half to even.
export function percent(ratio: number): string {
  const v = ratio * 100;
  const floor = Math.floor(v);
  const frac = v - floor;
  const r = frac > 0.5 ? floor + 1 : frac < 0.5 ? floor : floor % 2 === 0 ? floor : floor + 1;
  return `${r}%`;
}

export function normalize(raw: string): string {
  const text = raw
    .normalize('NFC')
    .replace(SOFT_HYPHEN, '')
    .replace(NOTE_REFERENCE, '')
    .replace(HYPHEN_AT_LINE_END, '$1$2')
    .replace(LINE_BREAK, ' ')
    .replace(RUN_OF_SPACES, ' ');
  return pyStrip(text);
}

// For comparing only. A character whose lowercase is more than one character
// (İ) is kept as it is, so the key has the text's length.
export function key(text: string): string {
  let out = '';
  for (const ch of text) {
    const mapped = KEY_MAP[ch] ?? ch;
    const low = mapped.toLowerCase();
    out += codePoints(low) === 1 ? low : mapped;
  }
  return out;
}

function keyOf(text: string): string {
  const k = key(text);
  if (k.length !== text.length) {
    throw new Error('matcher: key() changed a text\'s UTF-16 length; exact positions would not line up');
  }
  return k;
}

export type Page = { index: number; printed: number; text: string };
export type Hit = { text: string; page: number; pages: string; match: string };

type Text = { text: string; key: string; split: number; second: boolean };

// The work's pages in file order, normalized once, for looking quotations up.
export class Book {
  readonly pages: Page[];
  private readonly byPrinted = new Map<number, number>();
  private readonly norm: string[];
  private readonly keys: string[];

  constructor(pages: Page[]) {
    this.pages = pages;
    // A printed page scanned twice resolves to its first copy.
    pages.forEach((p, n) => {
      if (!this.byPrinted.has(p.printed)) this.byPrinted.set(p.printed, n);
    });
    this.norm = pages.map((p) => normalize(p.text));
    this.keys = this.norm.map(keyOf);
  }

  // Page n and page n+1 as one text, with where the second begins. A word
  // hyphenated across the break is joined, as within a page.
  private joined(n: number): Text | null {
    if (n + 1 >= this.pages.length) return null;
    const a = this.norm[n];
    const b = this.norm[n + 1];
    let text: string;
    let split: number;
    if (ENDS_IN_BROKEN_WORD.test(a) && STARTS_WITH_LETTER.test(b)) {
      text = a.slice(0, -1) + b;
      split = a.length - 1;
    } else {
      text = a + ' ' + b;
      split = a.length + 1;
    }
    return { text, key: keyOf(text), split, second: true };
  }

  // Positions to search, nearest first.
  private candidates(near: number | null, unit: number[] | null): number[] {
    const seen: number[] = [];
    if (near !== null && this.byPrinted.has(near)) {
      const c = this.byPrinted.get(near)!;
      for (const n of [c, c - 1, c + 1, c - 2, c + 2]) {
        if (n >= 0 && n < this.pages.length && !seen.includes(n)) seen.push(n);
      }
    }
    for (const n of unit ?? []) {
      if (!seen.includes(n)) seen.push(n);
    }
    return seen;
  }

  private exact(qkey: string, positions: number[]): Hit | null {
    for (const n of positions) {
      const at = this.keys[n].indexOf(qkey);
      if (at !== -1) return this.hit(n, this.norm[n].slice(at, at + qkey.length), 'exact', null);
    }
    for (const n of positions) {
      const j = this.joined(n);
      if (!j) continue;
      const at = j.key.indexOf(qkey);
      if (at !== -1) {
        const crosses = at < j.split && j.split <= at + qkey.length;
        const start = at < j.split ? n : n + 1;
        return this.hit(start, j.text.slice(at, at + qkey.length), 'exact', crosses ? n + 1 : null);
      }
    }
    return null;
  }

  private fuzzy(qkey: string, positions: number[]): Hit | null {
    const q = Array.from(qkey);
    const qlen = q.length;
    let best: { ratio: number; page: number; text: string; second: number | null } | null = null;
    for (const n of positions) {
      for (const t of this.texts(n)) {
        const blocks = matchingBlocks(q, Array.from(t.key)).filter((bl) => bl.size >= 3);
        if (blocks.length === 0) continue;
        const matched = blocks.reduce((sum, bl) => sum + bl.size, 0);
        const ratio = matched / qlen;
        const start = blocks[0].b;
        const last = blocks[blocks.length - 1];
        const end = last.b + last.size;
        const span = end - start;
        if (ratio < FUZZY_RATIO || !(0.85 * qlen <= span && span <= 1.2 * qlen)) continue;
        if (best === null || ratio > best.ratio) {
          // split is in code units; start and end are in characters.
          const split = t.second ? codePoints(t.text.slice(0, t.split)) : 0;
          const crosses = t.second && start < split && split <= end;
          const page = !t.second || start < split ? n : n + 1;
          const text = Array.from(t.text).slice(start, end).join('');
          best = { ratio, page, text, second: crosses ? n + 1 : null };
        }
      }
    }
    if (!best) return null;
    return this.hit(best.page, best.text, `close (${percent(best.ratio)})`, best.second);
  }

  private texts(n: number): Text[] {
    const out: Text[] = [{ text: this.norm[n], key: this.keys[n], split: 0, second: false }];
    const j = this.joined(n);
    if (j) out.push(j);
    return out;
  }

  private hit(n: number, text: string, match: string, second: number | null): Hit {
    const page = this.pages[n].printed;
    const pages = second !== null ? `${page}\u2013${this.pages[second].printed}` : String(page);
    return { text: pyStrip(text), page, pages, match };
  }

  // Exact on the named page and its neighbours (and the joins between them),
  // then the unit's pages, then the whole book; then a close match on the
  // named page and its neighbours only. near is a printed page; unit is a
  // list of positions in the book (dossier.py passes a chapter's; the MCP
  // tools pass none).
  find(quote: string, near: number | null, unit: number[] = []): Hit | null {
    const q = stripChars(normalize(quote), QUOTE_MARKS);
    if (codePoints(q) < MIN_QUOTE_CHARS) return null;
    const qkey = key(q);
    const nearPositions = this.candidates(near, null);
    const unitPositions = this.candidates(near, unit);
    return (
      this.exact(qkey, nearPositions) ??
      this.exact(qkey, unitPositions) ??
      this.exact(qkey, this.pages.map((_, n) => n)) ??
      this.fuzzy(qkey, nearPositions)
    );
  }
}
