-- Scriptorium — migration 010: the October 2026 lists
--
-- Generated by pipeline/relist.py from pipeline/reconcile.csv, which
-- reconcile.py produced from the department's final PDF.
--
-- The catalogue was built from an earlier version of the document. This
-- moves it onto the final one: sections dissolved and created, works
-- renumbered, thirty-seven works moved into Supplementary blocks.
--
-- Supplementary is examinable. The department counts it inside each
-- list's total and a supplementary work can carry a ficha in an axis,
-- so nothing here touches examinable_works.
--
-- Touches list_sections and list_items only. No work, note, anchor,
-- page or chunk is read or written. A work dropped from a list keeps
-- everything it has and becomes an off-list work.

begin;

-- Sections, in the order the document presents them ------------------
insert into list_sections (id, list_id, letter, title, kind, sort) values
  ('theory-narrative-theory-poetics-and-psychoanaly', 'theory', 'A', 'Narrative Theory, Poetics, and Psychoanalysis', 'core', 1),
  ('theory-haunting-archives-and-embodied-memory', 'theory', 'B', 'Haunting, Archives, and Embodied Memory', 'core', 2),
  ('theory-coloniality-possession-and-racial-geogra', 'theory', 'C', 'Coloniality, Possession, and Racial Geographies', 'core', 3),
  ('theory-chicana-feminisms-indigenous-knowledge-a', 'theory', 'D', 'Chicana Feminisms, Indigenous Knowledge, and Borderlands Religion', 'core', 4),
  ('theory-indigenous-studies-sovereignty-refusal-a', 'theory', 'E', 'Indigenous Studies: Sovereignty, Refusal, and Temporality', 'core', 5),
  ('theory-supplementary', 'theory', null, 'Supplementary', 'supplementary', 6),
  ('dissertation-colonial-narratives-inquisitorial-archiv', 'dissertation', 'A', 'Colonial Narratives, Inquisitorial Archives, and Territorial Formation', 'core', 1),
  ('dissertation-oral-tradition-regional-language-and-fol', 'dissertation', 'B', 'Oral Tradition, Regional Language, and Folklore Collection', 'core', 2),
  ('dissertation-witchcraft-healing-and-supernatural-enco', 'dissertation', 'C', 'Witchcraft, Healing, and Supernatural Encounters', 'core', 3),
  ('dissertation-literary-reworkings-and-comparative-indi', 'dissertation', 'D', 'Literary Reworkings and Comparative Indigenous Horror', 'core', 4),
  ('dissertation-hauntology-spectrality-and-historical-te', 'dissertation', 'E', 'Hauntology, Spectrality, and Historical Temporality', 'core', 5),
  ('dissertation-haunting-as-aesthetic-and-narrative-expe', 'dissertation', 'F', 'Haunting as Aesthetic and Narrative Experience: The Fantastic, the Gothic, and', 'core', 6),
  ('dissertation-chicana-spatial-criticism-borderlands-an', 'dissertation', 'G', 'Chicana Spatial Criticism, Borderlands, and Hemispheric Haunting', 'core', 7),
  ('dissertation-archival-criticism-documents-and-media', 'dissertation', 'H', 'Archival Criticism, Documents, and Media', 'core', 8),
  ('dissertation-nuevomexicano-cultural-history-and-gen-z', 'dissertation', 'I', 'Nuevomexicano Cultural History and Genízaro Identity', 'core', 9),
  ('dissertation-supplementary', 'dissertation', null, 'Supplementary', 'supplementary', 10),
  ('teaching-nation-race-and-revolution-in-mexican-li', 'teaching', 'A', 'Nation, Race, and Revolution in Mexican Literature', 'core', 1),
  ('teaching-mexican-american-print-culture-folklore-', 'teaching', 'B', 'Mexican American Print Culture, Folklore, and Chicano Cultural Nationalism', 'core', 2),
  ('teaching-chicana-feminisms-embodiment-and-cultura', 'teaching', 'C', 'Chicana Feminisms, Embodiment, and Cultural Memory', 'core', 3),
  ('teaching-migration-borders-and-cultural-translati', 'teaching', 'D', 'Migration, Borders, and Cultural Translation', 'core', 4),
  ('teaching-haunting-death-and-fantastic-narrative', 'teaching', 'E', 'Haunting, Death, and Fantastic Narrative', 'core', 5),
  ('teaching-teaching-practice-and-pedagogy', 'teaching', 'F', 'Teaching Practice and Pedagogy', 'core', 6),
  ('teaching-supplementary', 'teaching', null, 'Supplementary', 'supplementary', 7)
on conflict (id) do update set letter = excluded.letter, title = excluded.title, kind = excluded.kind, sort = excluded.sort;

-- Placement ----------------------------------------------------------
insert into list_items (list_id, work_id, section_id, ordinal) values
  -- Aristóteles — Poética
  ('theory', 'aristoteles-poetica-1974', 'theory-narrative-theory-poetics-and-psychoanaly', 1),
  -- Freud, Sigmund — “Lo ominoso.” 1919
  ('theory', 'freud-el-malestar-en-la-cultura-1978', 'theory-narrative-theory-poetics-and-psychoanaly', 2),
  -- Lacan, Jacques — “El seminario sobre ‘La carta robada.’” 
  ('theory', 'lacan-escritos-1-2012', 'theory-narrative-theory-poetics-and-psychoanaly', 3),
  -- Lienhard, Martín — La voz y su huella: escritura y conflict
  ('theory', 'lienhard-la-voz-y-su-huella-1990', 'theory-narrative-theory-poetics-and-psychoanaly', 4),
  -- Pimentel, Luz Aurora — El relato en perspectiva: estudio de teo
  ('theory', 'pimentel-el-relato-en-perspectiva-estudio-1998', 'theory-narrative-theory-poetics-and-psychoanaly', 5),
  -- Rama, Ángel — Transculturación narrativa en América La
  ('theory', 'rama-transculturacion-narrativa-en-america-la-1982', 'theory-narrative-theory-poetics-and-psychoanaly', 6),
  -- Viego, Antonio — Dead Subjects: Toward a Politics of Loss
  ('theory', 'viego-dead-subjects-toward-2007', 'theory-narrative-theory-poetics-and-psychoanaly', 7),
  -- Derrida, Jacques — Mal de archivo: una impresión freudiana
  ('theory', 'derrida-mal-de-archivo-una-impresion-1997', 'theory-haunting-archives-and-embodied-memory', 8),
  -- Gordon, Avery F — Ghostly Matters: Haunting and the Sociol
  ('theory', 'gordon-ghostly-matters-haunting-and-the-1997', 'theory-haunting-archives-and-embodied-memory', 9),
  -- Molloy, Sylvia — Acto de presencia: la escritura autobiog
  ('theory', 'molloy-acto-de-presencia-la-escritura-1996', 'theory-haunting-archives-and-embodied-memory', 10),
  -- Stoler, Ann Laura — Along the Archival Grain: Epistemic Anxi
  ('theory', 'stoler-along-the-archival-grain-epistemic-2009', 'theory-haunting-archives-and-embodied-memory', 11),
  -- Taylor, Diana — The Archive and the Repertoire: Performi
  ('theory', 'taylor-the-archive-and-the-repertoire-2003', 'theory-haunting-archives-and-embodied-memory', 12),
  -- Adorno, Rolena — The Polemics of Possession in Spanish Am
  ('theory', 'adorno-the-polemics-of-possession-in-2007', 'theory-coloniality-possession-and-racial-geogra', 13),
  -- Gerhard, Peter — La frontera norte de la Nueva España
  ('theory', 'gerhard-la-frontera-norte-de-la-1996', 'theory-coloniality-possession-and-racial-geogra', 14),
  -- Gómez-Barris, Macarena — The Extractive Zone: Social Ecologies an
  ('theory', 'gomez-barris-the-extractive-zone-social-ecologies-2017', 'theory-coloniality-possession-and-racial-geogra', 15),
  -- Jáuregui, Carlos A — Espectros y conjuras: asedios a la cuest
  ('theory', 'jauregui-espectros-y-conjuras-asedios-a-2020', 'theory-coloniality-possession-and-racial-geogra', 16),
  -- Saldaña-Portillo, María Jose — Indian Given: Racial Geographies across 
  ('theory', 'saldana-portillo-indian-given-racial-geographies-across-2016', 'theory-coloniality-possession-and-racial-geogra', 17),
  -- Taussig, Michael — Shamanism, Colonialism, and the Wild Man
  ('theory', 'taussig-shamanism-colonialism-and-the-wild-1987', 'theory-coloniality-possession-and-racial-geogra', 18),
  -- Anzaldúa, Gloria — Borderlands / La Frontera: The New Mesti
  ('theory', 'anzaldua-borderlands-la-frontera-the-new-1987', 'theory-chicana-feminisms-indigenous-knowledge-a', 19),
  -- Castillo, Ana — Massacre of the Dreamers: Essays on Xica
  ('theory', 'castillo-massacre-of-the-dreamers-essays-1994', 'theory-chicana-feminisms-indigenous-knowledge-a', 20),
  -- Delgado, Vivian — You’re Not Indian, You’re Mexican
  ('theory', 'delgado-you-re-not-indian-you-2007', 'theory-chicana-feminisms-indigenous-knowledge-a', 21),
  -- Gonzales, Patrisia — Red Medicine: Traditional Indigenous Rit
  ('theory', 'gonzales-red-medicine-traditional-indigenous-rite-2012', 'theory-chicana-feminisms-indigenous-knowledge-a', 22),
  -- León, Luis D — La Llorona’s Children: Religion, Life, a
  ('theory', 'leon-la-llorona-s-children-religion-2004', 'theory-chicana-feminisms-indigenous-knowledge-a', 23),
  -- Koshatka Seman, Jennifer — Border Curanderos
  ('theory', 'seman-border-curanderos-2021', 'theory-chicana-feminisms-indigenous-knowledge-a', 24),
  -- Simpson, Audra — Mohawk Interruptus: Political Life acros
  ('theory', 'simpson-mohawk-interruptus-political-life-across-2014', 'theory-indigenous-studies-sovereignty-refusal-a', 25),
  -- Schaeffer, Felicity Amaya — Unsettled Borders: The Militarized Scien
  ('theory', 'schaeffer-unsettled-borders-the-militarized-scienc-2022', 'theory-indigenous-studies-sovereignty-refusal-a', 26),
  -- Segato, Rita Laura — La crítica de la colonialidad en ocho en
  ('theory', 'segato-la-critica-de-la-colonialidad-2021', 'theory-supplementary', 27),
  -- Rifkin, Mark — Beyond Settler Time: Temporal Sovereignt
  ('theory', 'rifkin-beyond-settler-time-temporal-sovereignty-2017', 'theory-supplementary', 28),
  -- Cornejo Polar, Antonio — Escribir en el aire: ensayo sobre la het
  ('theory', 'cornejo-polar-escribir-en-el-aire-ensayo-1994', 'theory-supplementary', 29),
  -- Jelin, Elizabeth — Los trabajos de la memoria
  ('theory', 'jelin-los-trabajos-de-la-memoria-2002', 'theory-supplementary', 30),
  -- Fong, Timothy P — Ethnic Studies Research: Approaches and 
  ('theory', 'fong-ethnic-studies-research-approaches-and-2008', 'theory-supplementary', 31),
  -- Sanjek, Roger, editor — Fieldnotes: The Makings of Anthropology
  ('theory', 'sanjek-fieldnotes-the-makings-of-anthropology-1990', 'theory-supplementary', 32),
  -- Cabeza de Vaca, Álvar Núñez — Naufragios
  ('dissertation', 'cabeza-de-vaca-naufragios-1989', 'dissertation-colonial-narratives-inquisitorial-archiv', 1),
  -- Villagrá, Gaspar Pérez de — Historia de la Nueva México
  ('dissertation', 'villagra-historia-de-la-nueva-mexico-2010', 'dissertation-colonial-narratives-inquisitorial-archiv', 2),
  -- Flores, Enrique, y Mariana M — Relatos populares de la Inquisición novo
  ('dissertation', 'flores-relatos-populares-de-la-inquisicion-2010', 'dissertation-colonial-narratives-inquisitorial-archiv', 3),
  -- Ebright, Malcolm, y Rick Hen — The Witches of Abiquiu: The Governor, th
  ('dissertation', 'ebright-the-witches-of-abiquiu-the-2006', 'dissertation-colonial-narratives-inquisitorial-archiv', 4),
  -- Espinosa, Aurelio M — The Folklore of Spain in the American So
  ('dissertation', 'espinosa-the-folklore-of-spain-in-1985', 'dissertation-oral-tradition-regional-language-and-fol', 5),
  -- Espinosa, J — Manuel, recopilador
  ('dissertation', 'espinosa-cuentos-de-cuanto-hay-tales-1998', 'dissertation-oral-tradition-regional-language-and-fol', 6),
  -- Griego y Maestas, José, y Ru — Anaya, editores
  ('dissertation', 'griego-y-maestas-cuentos-tales-from-the-hispanic-1980', 'dissertation-oral-tradition-regional-language-and-fol', 7),
  -- Pijoan de Van Etten, Teresa — Spanish-American Folktales: The Practica
  ('dissertation', 'pijoan-de-van-etten-spanish-american-folktales-the-practical-1990', 'dissertation-oral-tradition-regional-language-and-fol', 8),
  -- Rael, Juan B — Cuentos españoles de Colorado y Nuevo Mé
  ('dissertation', 'rael-cuentos-espanoles-de-colorado-y-1977', 'dissertation-oral-tradition-regional-language-and-fol', 9),
  -- Rebolledo, Tey Diana, y Marí — Women’s Tales from the New Mexico WPA: L
  ('dissertation', 'rebolledo-women-s-tales-from-the-2000', 'dissertation-oral-tradition-regional-language-and-fol', 10),
  -- Vigil, Ángel, recopilador — The Corn Woman: Stories and Legends of t
  ('dissertation', 'vigil-the-corn-woman-stories-and-1994', 'dissertation-oral-tradition-regional-language-and-fol', 11),
  -- Delgado, Edmundo R — Witch Stories of New Mexico: Folklore of
  ('dissertation', 'delgado-witch-stories-of-new-mexico-1994', 'dissertation-witchcraft-healing-and-supernatural-enco', 12),
  -- García, Nasario, recopilador — Brujas, bultos, y brasas: Tales of Witch
  ('dissertation', 'garcia-brujas-bultos-y-brasas-tales-1999', 'dissertation-witchcraft-healing-and-supernatural-enco', 13),
  -- García, Nasario — Brujerías: Stories of Witchcraft and the
  ('dissertation', 'garcia-brujerias-stories-of-witchcraft-and-2007', 'dissertation-witchcraft-healing-and-supernatural-enco', 14),
  -- Kraul, Edward Garcia, y Judi — The Weeping Woman: Encounters with La Ll
  ('dissertation', 'kraul-the-weeping-woman-encounters-with-1988', 'dissertation-witchcraft-healing-and-supernatural-enco', 15),
  -- Antonio R — American Indian Ghost Stories of the Wes
  ('dissertation', 'garcez-american-indian-ghost-stories-of-2003', 'dissertation-literary-reworkings-and-comparative-indi', 16),
  -- Sagel, Jim — Hablando de brujas y la gente de antes: 
  ('dissertation', 'sagel-hablando-de-brujas-y-la-1981', 'dissertation-literary-reworkings-and-comparative-indi', 17),
  -- Abudu, KJ, editor — Living with Ghosts: A Reader
  ('dissertation', 'abudu-living-with-ghosts-a-reader-2022', 'dissertation-hauntology-spectrality-and-historical-te', 18),
  -- Derrida, Jacques — Specters of Marx: The State of the Debt,
  ('dissertation', 'derrida-specters-of-marx-the-state-1994', 'dissertation-hauntology-spectrality-and-historical-te', 19),
  -- Weinstock, Jeffrey Andrew, e — Spectral America: Phantoms and the Natio
  ('dissertation', 'weinstock-spectral-america-phantoms-and-the-2004', 'dissertation-hauntology-spectrality-and-historical-te', 20),
  -- Fisher, Mark — The Weird and the Eerie
  ('dissertation', 'fisher-the-weird-and-the-eerie-2017', 'dissertation-hauntology-spectrality-and-historical-te', 21),
  -- Keetley, Dawn, y Ruth Heholt — Folk Horror: New Global Pathways
  ('dissertation', 'keetley-folk-horror-new-global-pathways-2023', 'dissertation-haunting-as-aesthetic-and-narrative-expe', 22),
  -- Todorov, Tzvetan — The Fantastic: A Structural Approach to 
  ('dissertation', 'todorov-the-fantastic-a-structural-approach-1975', 'dissertation-haunting-as-aesthetic-and-narrative-expe', 23),
  -- Walter, Roland — Magical Realism in Contemporary Chicano 
  ('dissertation', 'walter-magical-realism-in-contemporary-chicano-1993', 'dissertation-haunting-as-aesthetic-and-narrative-expe', 24),
  -- Blanco, María del Pilar — Ghost-Watching American Modernity: Haunt
  ('dissertation', 'blanco-ghost-watching-american-modernity-haunti-2012', 'dissertation-chicana-spatial-criticism-borderlands-an', 25),
  -- Brady, Mary Pat — Extinct Lands, Temporal Geographies: Chi
  ('dissertation', 'brady-extinct-lands-temporal-geographies-chica-2002', 'dissertation-chicana-spatial-criticism-borderlands-an', 26),
  -- Perez, Domino Renee — There Was a Woman: La Llorona from Folkl
  ('dissertation', 'perez-there-was-a-woman-la-2008', 'dissertation-chicana-spatial-criticism-borderlands-an', 27),
  -- Bolaños, Álvaro Félix, y Gus — Colonialism Past and Present: Reading an
  ('dissertation', 'bolanos-colonialism-past-and-present-reading-2002', 'dissertation-archival-criticism-documents-and-media', 28),
  -- Moraña, Mabel, Enrique Dusse — Jáuregui, editores
  ('dissertation', 'morana-coloniality-at-large-latin-america-2008', 'dissertation-archival-criticism-documents-and-media', 29),
  -- Gonzales, Moises, y Enrique  — Lamadrid, editores
  ('dissertation', 'gonzales-nacion-genizara-ethnogenesis-place-and-2019', 'dissertation-nuevomexicano-cultural-history-and-gen-z', 30),
  -- Padilla, Genaro M — My History, Not Yours: The Formation of 
  ('dissertation', 'padilla-my-history-not-yours-the-1993', 'dissertation-supplementary', 31),
  -- Briggs, Charles L — Competence in Performance: The Creativit
  ('dissertation', 'briggs-competence-in-performance-the-creativity-1988', 'dissertation-supplementary', 32),
  -- Rama, Ángel — La ciudad letrada
  ('dissertation', 'rama-la-ciudad-letrada-1984', 'dissertation-supplementary', 33),
  -- Cobos, Rubén — A Dictionary of New Mexico and Southern 
  ('dissertation', 'cobos-a-dictionary-of-new-mexico-2003', 'dissertation-supplementary', 34),
  -- Gitelman, Lisa — Paper Knowledge: Toward a Media History 
  ('dissertation', 'gitelman-paper-knowledge-toward-a-media-2014', 'dissertation-supplementary', 35),
  -- Burns, Kathryn — Into the Archive: Writing and Power in C
  ('dissertation', 'burns-into-the-archive-writing-and-2010', 'dissertation-supplementary', 36),
  -- Brady, Mary Pat — Scales of Captivity: Racial Capitalism a
  ('dissertation', 'brady-scales-of-captivity-racial-capitalism-2022', 'dissertation-supplementary', 37),
  -- Hawk, Shane, y Theodore C — Van Alst Jr., editores
  ('dissertation', 'hawk-never-whistle-at-night-an-2023', 'dissertation-supplementary', 38),
  -- Meléndez, A — Gabriel
  ('dissertation', 'melendez-so-all-is-not-lost-1997', 'dissertation-supplementary', 39),
  -- Rabasa, José — Without History: Subaltern Studies, the 
  ('dissertation', 'rabasa-without-history-subaltern-studies-the-2010', 'dissertation-supplementary', 40),
  -- Ortega, Élika — Binding Media: Hybrid Print-Digital Lite
  ('dissertation', 'ortega-binding-media-hybrid-print-digital-2025', 'dissertation-supplementary', 41),
  -- Boj López, Floridalma — Indigenous Archives: The Maya Diaspora a
  ('dissertation', 'boj-lopez-indigenous-archives-the-maya-diaspora-2026', 'dissertation-supplementary', 42),
  -- Fisher, Mark — Ghosts of My Life: Writings on Depressio
  ('dissertation', 'fisher-ghosts-of-my-life-writings-2014', 'dissertation-supplementary', 43),
  -- Spooner, Catherine — Contemporary Gothic
  ('dissertation', 'spooner-contemporary-gothic-2006', 'dissertation-supplementary', 44),
  -- Campra, Rosalba — Territorios de la ficción: lo fantástico
  ('dissertation', 'campra-territorios-de-la-ficcion-lo-2008', 'dissertation-supplementary', 45),
  -- Keetley, Dawn — Folk Gothic
  ('dissertation', 'keetley-folk-gothic-2024', 'dissertation-supplementary', 46),
  -- Padilla, Genaro — The Daring Flight of My Pen: Cultural Po
  ('dissertation', 'padilla-the-daring-flight-of-my-2010', 'dissertation-supplementary', 47),
  -- Scovell, Adam — Folk Horror: Hours Dreadful and Things S
  ('dissertation', 'scovell-folk-horror-hours-dreadful-and-2017', 'dissertation-supplementary', 48),
  -- Méndez, María Águeda, coordi — Catálogo de textos marginados novohispan
  ('dissertation', 'mendez-catalogo-de-textos-marginados-novohispan-1992', 'dissertation-supplementary', 49),
  -- Mignolo, Walter — Teoría del texto e interpretación de tex
  ('dissertation', 'mignolo-teoria-del-texto-e-interpretacion-1986', 'dissertation-supplementary', 50),
  -- Rodríguez, Gregorita — Singing for My Echo: Memories of Gregori
  ('dissertation', 'rodriguez-singing-for-my-echo-memories-1987', 'dissertation-supplementary', 51),
  -- Fernández de Lizardi, José J — El Periquillo Sarniento
  ('teaching', 'fernandez-de-lizardi-el-periquillo-sarniento-1816', 'teaching-nation-race-and-revolution-in-mexican-li', 1),
  -- Payno, Manuel — Los bandidos de Río Frío
  ('teaching', 'payno-los-bandidos-de-rio-frio-1891', 'teaching-nation-race-and-revolution-in-mexican-li', 2),
  -- Frías, Heriberto — Tomóchic
  ('teaching', 'frias-tomochic-1893', 'teaching-nation-race-and-revolution-in-mexican-li', 3),
  -- Azuela, Mariano — Los de abajo
  ('teaching', 'azuela-los-de-abajo-1915', 'teaching-nation-race-and-revolution-in-mexican-li', 4),
  -- Vasconcelos, José — La raza cósmica: misión de la raza ibero
  ('teaching', 'vasconcelos-la-raza-cosmica-1925', 'teaching-nation-race-and-revolution-in-mexican-li', 5),
  -- Campobello, Nellie — Cartucho: relatos de la lucha en el nort
  ('teaching', 'campobello-cartucho-1931', 'teaching-nation-race-and-revolution-in-mexican-li', 6),
  -- Revueltas, José — El luto humano
  ('teaching', 'revueltas-el-luto-humano-1943', 'teaching-nation-race-and-revolution-in-mexican-li', 7),
  -- Paz, Octavio — El laberinto de la soledad
  ('teaching', 'paz-el-laberinto-de-la-soledad-1950', 'teaching-nation-race-and-revolution-in-mexican-li', 8),
  -- Fuentes, Carlos — La muerte de Artemio Cruz
  ('teaching', 'fuentes-la-muerte-de-artemio-cruz-1962', 'teaching-nation-race-and-revolution-in-mexican-li', 9),
  -- Arce, Julio G — [Jorge Ulica]
  ('teaching', 'arce-cronicas-diabolicas-1916-1926-1982', 'teaching-mexican-american-print-culture-folklore-', 10),
  -- Venegas, Daniel — Las aventuras de don Chipote o Cuando lo
  ('teaching', 'venegas-las-aventuras-de-don-chipote-1928', 'teaching-mexican-american-print-culture-folklore-', 11),
  -- Paredes, Américo — “With His Pistol in His Hand”: A Border 
  ('teaching', 'paredes-with-his-pistol-in-his-1958', 'teaching-mexican-american-print-culture-folklore-', 12),
  -- Gonzales, Rodolfo “Corky — 1967
  ('teaching', 'gonzales-yo-soy-joaquin-1967', 'teaching-mexican-american-print-culture-folklore-', 13),
  -- Rivera, Tomás — …y no se lo tragó la tierra / …And the E
  ('teaching', 'rivera-y-no-se-lo-trago-1996', 'teaching-mexican-american-print-culture-folklore-', 14),
  -- La Chrisx — “La loca de la raza cósmica.” 1978
  ('teaching', 'la-chrisx-la-loca-de-la-raza-1978', 'teaching-mexican-american-print-culture-folklore-', 15),
  -- Corpi, Lucha — Palabras de mediodía / Noon Words
  ('teaching', 'corpi-palabras-de-mediodia-noon-words-1980', 'teaching-chicana-feminisms-embodiment-and-cultura', 16),
  -- Viramontes, Helena María — The Moths and Other Stories
  ('teaching', 'viramontes-the-moths-and-other-stories-1985', 'teaching-chicana-feminisms-embodiment-and-cultura', 17),
  -- Chávez, Denise — Loving Pedro Infante
  ('teaching', 'chavez-loving-pedro-infante-2001', 'teaching-chicana-feminisms-embodiment-and-cultura', 18),
  -- Fajardo-Anstine, Kali — Sabrina & Corina: Stories
  ('teaching', 'fajardo-anstine-sabrina-corina-stories-2019', 'teaching-chicana-feminisms-embodiment-and-cultura', 19),
  -- Jiménez, Francisco — Cajas de cartón: relatos de la vida pere
  ('teaching', 'jimenez-cajas-de-carton-2002', 'teaching-migration-borders-and-cultural-translati', 20),
  -- Jiménez, Francisco — Cajas de cartón: relatos de la vida pere
  ('teaching', 'jimenez-senderos-fronterizos-2002', 'teaching-migration-borders-and-cultural-translati', 20),
  -- Alarcón, Francisco X — From the Other Side of Night / Del otro 
  ('teaching', 'alarcon-from-the-other-side-of-2002', 'teaching-migration-borders-and-cultural-translati', 21),
  -- Grande, Reyna — A través de cien montañas
  ('teaching', 'grande-a-traves-de-cien-montanas-2007', 'teaching-migration-borders-and-cultural-translati', 22),
  -- Urrea, Luis Alberto — The Devil’s Highway
  ('teaching', 'urrea-devil-s-highway-2004', 'teaching-migration-borders-and-cultural-translati', 23),
  -- Castillo, Marcelo Hernandez — Children of the Land: A Memoir
  ('teaching', 'castillo-children-land-memoir-2020', 'teaching-migration-borders-and-cultural-translati', 24),
  -- Rulfo, Juan — El llano en llamas
  ('teaching', 'rulfo-el-llano-en-llamas-1955', 'teaching-haunting-death-and-fantastic-narrative', 25),
  -- Rulfo, Juan — El llano en llamas
  ('teaching', 'rulfo-pedro-paramo-1955', 'teaching-haunting-death-and-fantastic-narrative', 25),
  -- Anaya, Rudolfo — Bless Me, Ultima
  ('teaching', 'anaya-bless-me-ultima-1972', 'teaching-haunting-death-and-fantastic-narrative', 26),
  -- Arias, Ron — El camino a Tamazunchale
  ('teaching', 'arias-el-camino-a-tamazunchale-2002', 'teaching-haunting-death-and-fantastic-narrative', 27),
  -- Valdemar García, Itz-Ollin — La casa del brujo / The Sorcerer’s House
  ('teaching', 'valdemar-garcia-la-casa-del-brujo-the-1984', 'teaching-haunting-death-and-fantastic-narrative', 28),
  -- Anzaldúa, Gloria — Prietita and the Ghost Woman
  ('teaching', 'anzaldua-prietita-and-the-ghost-woman-1995', 'teaching-haunting-death-and-fantastic-narrative', 29),
  -- Méndez, Miguel — Los muertos también cuentan
  ('teaching', 'mendez-los-muertos-tambien-cuentan-1995', 'teaching-haunting-death-and-fantastic-narrative', 30),
  -- Herrera, Yuri — La transmigración de los cuerpos
  ('teaching', 'herrera-la-transmigracion-de-los-cuerpos-2013', 'teaching-haunting-death-and-fantastic-narrative', 31),
  -- Rivera Garza, Cristina — Los muertos indóciles: necroescrituras y
  ('teaching', 'rivera-garza-los-muertos-indociles-necroescrituras-y-2013', 'teaching-haunting-death-and-fantastic-narrative', 32),
  -- Fragoza, Carribean — Eat the Mouth That Feeds You
  ('teaching', 'fragoza-eat-the-mouth-that-feeds-2021', 'teaching-haunting-death-and-fantastic-narrative', 33),
  -- Dávila, Amparo — Cuentos reunidos
  ('teaching', 'davila-cuentos-reunidos', 'teaching-haunting-death-and-fantastic-narrative', 34),
  -- Sánchez Prado, Ignacio M — Teaching the Mexican Revolution
  ('teaching', 'sanchez-prado-teaching-the-mexican-revolution-2026', 'teaching-teaching-practice-and-pedagogy', 35),
  -- Luiselli, Valeria — Los niños perdidos: un ensayo en cuarent
  ('teaching', 'luiselli-los-ninos-perdidos-un-ensayo-2016', 'teaching-supplementary', 36),
  -- Castillo, Ana — The Guardians
  ('teaching', 'castillo-the-guardians-2007', 'teaching-supplementary', 37),
  -- Gómez-Peña, Guillermo — Bitácora del cruce
  ('teaching', 'gomez-pena-bitacora-del-cruce-2006', 'teaching-supplementary', 38),
  -- Díaz, Natalie — Postcolonial Love Poem
  ('teaching', 'diaz-postcolonial-love-poem-2020', 'teaching-supplementary', 39),
  -- Pineda, Irma — Nostalgia Doesn’t Flow Away Like Riverwa
  ('teaching', 'pineda-nostalgia-doesn-t-flow-away-2024', 'teaching-supplementary', 40),
  -- Martínez, Elizabeth Coonrod, — Teaching Late-Twentieth-Century Mexicana
  ('teaching', 'martinez-teaching-late-twentieth-century-mexicana-2020', 'teaching-supplementary', 41),
  -- Moraga, Cherríe — A Xicana Codex of Changing Consciousness
  ('teaching', 'moraga-a-xicana-codex-of-changing-2011', 'teaching-supplementary', 42),
  -- Cisneros, Sandra — Woman Hollering Creek and Other Stories
  ('teaching', 'cisneros-woman-hollering-creek-and-other-1991', 'teaching-supplementary', 43),
  -- Meléndez, A — Gabriel, editor
  ('teaching', 'melendez-ciudadanos-por-tratado-textos-de-2025', 'teaching-supplementary', 44),
  -- Mohamed Ihab Bebars, Nehad — Voces femeninas en el cuento mexicano de
  ('teaching', 'mohamed-ihab-bebars-voces-femeninas-en-el-cuento-2012', 'teaching-supplementary', 45),
  -- Alberro, Solange — Inquisición y sociedad en México, 1571–1
  ('working-bibliography', 'alberro-inquisicion-y-sociedad-en-mexico-1988', null, 1),
  -- Aguilar Gil, Yásnaya Elena — Ää: manifiestos sobre la diversidad ling
  ('working-bibliography', 'aguilar-gil-aa-manifiestos-sobre-la-diversidad-2020', null, 2),
  -- Beverley, John — Testimonio: On the Politics of Truth
  ('working-bibliography', 'beverley-testimonio-on-the-politics-of-2004', null, 3),
  -- Brooks, James F — Captives and Cousins: Slavery, Kinship, 
  ('working-bibliography', 'brooks-captives-and-cousins-slavery-kinship-2002', null, 4),
  -- Ebright, Malcolm — Land Grants and Lawsuits in Northern New
  ('working-bibliography', 'ebright-land-grants-and-lawsuits-in-1994', null, 5),
  -- Gutiérrez, Ramón A — When Jesus Came, the Corn Mothers Went A
  ('working-bibliography', 'gutierrez-when-jesus-came-the-corn-1991', null, 6),
  -- Hendrickson, Brett — Border Medicine: A Transcultural History
  ('working-bibliography', 'hendrickson-border-medicine-a-transcultural-history-2014', null, 7),
  -- Hirsch, Marianne — The Generation of Postmemory: Writing an
  ('working-bibliography', 'hirsch-the-generation-of-postmemory-writing-2012', null, 8),
  -- Jones, Stephen Graham — The Only Good Indians
  ('working-bibliography', 'jones-the-only-good-indians-2020', null, 9),
  -- Justice, Daniel Heath — Why Indigenous Literatures Matter
  ('working-bibliography', 'justice-why-indigenous-literatures-matter-2018', null, 10),
  -- Melchor, Fernanda — Temporada de huracanes
  ('working-bibliography', 'melchor-temporada-de-huracanes-2017', null, 11),
  -- Meléndez, A — Gabriel
  ('working-bibliography', 'melendez-hidden-chicano-cinema-film-dramas-2013', null, 12),
  -- Meyer, Doris — Speaking for Themselves: Neomexicano Cul
  ('working-bibliography', 'meyer-speaking-for-themselves-neomexicano-cult-1996', null, 13),
  -- Nieto-Phillips, John M — The Language of Blood: The Making of Spa
  ('working-bibliography', 'nieto-phillips-the-language-of-blood-the-2004', null, 14),
  -- Rappaport, Joanne, y Tom Cum — Beyond the Lettered City: Indigenous Lit
  ('working-bibliography', 'rappaport-beyond-the-lettered-city-indigenous-2012', null, 15),
  -- Sklodowska, Elzbieta — Testimonio hispanoamericano: historia, t
  ('working-bibliography', 'sklodowska-testimonio-hispanoamericano-historia-teo-1992', null, 16),
  -- Weigle, Marta — Brothers of Light, Brothers of Blood: Th
  ('working-bibliography', 'weigle-brothers-of-light-brothers-of-1976', null, 17),
  -- Steinauer-Scudder, Chelsea — “Counter Mapping.” Emergence Magazine, 8
  ('working-bibliography', 'counter-mapping-https--counter-mapping', null, 18),
  -- Sagás, Ernesto — Latino Colorado: The Struggle for Equali
  ('working-bibliography', 'sagas-latino-colorado', null, 19),
  -- Akerman, Chantal, directora — De l’autre côté
  ('filmography', 'akerman-de-l-autre-cote-2002', null, 1),
  -- Almada, Natalia, directora — El velador
  ('filmography', 'almada-el-velador-2011', null, 2),
  -- Arteaga, Marcela, directora — El guardián de la memoria
  ('filmography', 'arteaga-el-guardian-de-la-memoria-2019', null, 3),
  -- Esteinou, Santiago, Javier C — Mukí Sopalírili Aligué Gawichí Nirúgame 
  ('filmography', 'esteinou-muki-sopalirili-aligue-gawichi-nirugame-2023', null, 4),
  -- Huezo, Tatiana, directora — Tempestad
  ('filmography', 'huezo-tempestad-2016', null, 5),
  -- Portillo, Lourdes, directora — Señorita extraviada
  ('filmography', 'portillo-senorita-extraviada-2001', null, 6),
  -- Reggio, Godfrey, director — Visitors
  ('filmography', 'reggio-visitors-2013', null, 7),
  -- Rivera, Alex, director — Sleep Dealer
  ('filmography', 'rivera-sleep-dealer-2008', null, 8),
  -- Ruiz, Bernardo, director — Kingdom of Shadows
  ('filmography', 'ruiz-kingdom-of-shadows-2015', null, 9),
  -- Rulfo, Juan Carlos, y Carlos — Los que se quedan
  ('filmography', 'rulfo-los-que-se-quedan-2008', null, 10),
  -- López, Issa, directora — Vuelven
  ('filmography', 'lopez-vuelven', null, 11),
  -- Lyon, Danny, director — Llanito
  ('filmography', 'lyon-llanito-1971', null, 12),
  -- Price, Roland, y Harry J — Revier, directores
  ('filmography', 'price-lash-penitentes-1936', null, 13)
on conflict (list_id, work_id) do update set section_id = excluded.section_id, ordinal = excluded.ordinal;

-- Off the list -------------------------------------------------------
--
-- One membership row each. The works themselves, and every note,
-- quotation and page belonging to them, are untouched: they become
-- off-list works, the same state a work added by hand arrives in.
delete from list_items where list_id = 'dissertation' and work_id = 'schaeffer-unsettled-borders-the-militarized-scienc-2022';
delete from list_items where list_id = 'theory' and work_id = 'williams-the-other-side-of-the-2002';

update works set standing = 'added', updated_at = now()
where id in ('schaeffer-unsettled-borders-the-militarized-scienc-2022', 'williams-the-other-side-of-the-2002')
  and not exists (select 1 from list_items li where li.work_id = works.id);

commit;

-- After running, confirm the counts against the document's own header:
--   Theory 29 · Dissertation 52 · Teaching 41
--
--   select l.name, s.title, count(*)
--   from list_items li
--   join exam_lists l on l.id = li.list_id
--   left join list_sections s on s.id = li.section_id
--   group by l.name, s.title order by l.name, s.title;
