-- Scriptorium — link source files to catalogue records
--
-- Generated by pipeline/link.py from triage.csv and mapping.csv.
-- Re-runnable. Review before running: this mapping is what every
-- citation and every note anchor depends on.
--
-- 23 files mapped to 21 books.

begin;
update books set
  source_format = 'pdf_text',
  source_path   = 'pipeline/corpus/Rolena Adorno_Polemics of Possesion.pdf',
  updated_at    = now()
where id = 'adorno-polemics-possession-2007';

update books set
  source_format = 'pdf_text',
  source_path   = 'pipeline/corpus/Cuentos_ Tales from the Hispanic Southwest_ Based on Stories -- selected by and adapted in Spanish by José Griego y Maestas; -- Santa Fe, N_M, ©1980, -- 9780890131107 -- 73a969f2aaeb372fbafdf4c9fbe476bf -- Anna’s Archive.pdf',
  updated_at    = now()
where id = 'anaya-cuentos-hispanic-southwest-1980';

update books set
  source_format = 'pdf_text',
  source_path   = 'pipeline/corpus/El camino a Tamazunchale -- Arias, Ron, 1941- -- Tempe, Ariz, Arizona, 2002 -- Tempe, Ariz_ _ Bilingual Press_Editorial Bilingüe -- isbn13 9781931010061 -- 6f9e283a001461002472741a1ea9515c -- Anna’s Archive.pdf',
  updated_at    = now()
where id = 'arias-camino-tamazunchale-1975';

update books set
  source_format = 'pdf_ocr',
  source_path   = 'pipeline/corpus/Diccionario Cobos sur Colorado español.pdf',
  notes_internal = coalesce(notes_internal || ' | ', '') || '29pp of a much longer dictionary — excerpt',
  updated_at    = now()
where id = 'cobos-dictionary-nm-spanish-2003';

update books set
  source_format = 'pdf_text',
  source_path   = 'pipeline/corpus/Mal de archivo_ una impresión freudiana -- Jacques Derrida; Paco Vidarte -- Estructuras y Procesos_ Filosofía, 1a, 1997 -- Trotta Trotta -- isbn13 9788481641332 -- 1991aab86a9a6c8f86857e8e412f18a1 -- Anna’s Archi.pdf',
  updated_at    = now()
where id = 'derrida-mal-de-archivo-1995';

update books set
  source_format = 'pdf_text',
  source_path   = 'pipeline/corpus/Flores - Inquisición.pdf',
  updated_at    = now()
where id = 'flores-masera-relatos-inquisicion-2010';

update books set
  source_format = 'pdf_text',
  source_path   = 'pipeline/corpus/La frontera norte de la nueva españa.pdf',
  notes_internal = coalesce(notes_internal || ' | ', '') || '28pp — excerpt',
  updated_at    = now()
where id = 'gerhard-frontera-norte-1996';

update books set
  source_format = 'pdf_text',
  source_path   = 'pipeline/corpus/The extractive zone_Macarena.pdf',
  updated_at    = now()
where id = 'gomez-barris-extractive-zone-2017';

update books set
  source_format = 'pdf_text',
  source_path   = 'pipeline/corpus/Red_Medicine_Traditional_Indigenous_Rites_of_Birth....pdf',
  updated_at    = now()
where id = 'gonzales-red-medicine-2012';

update books set
  source_format = 'pdf_text',
  source_path   = 'pipeline/corpus/La transmigración de los cuerpos_Yuri Herrera.pdf',
  updated_at    = now()
where id = 'herrera-transmigracion-cuerpos-2013';

update books set
  source_format = 'pdf_text',
  source_path   = 'pipeline/corpus/Espectros y conjuras- Asedios a la cuestión colonial -- Carlos A_ Jáuregui -- Parecos y australes_ Ensayos de Cultura de la Colonia; 25, -- Vervuert -- 9783964568182 -- a8875767c5758e8601e5925013373a26 -- Anna’s Archive.pdf',
  updated_at    = now()
where id = 'jauregui-espectros-conjuras-2020';

update books set
  source_format = 'pdf_text',
  source_path   = 'pipeline/corpus/Estructura Del Texto Artistico (Coleccion Fundamentos, 58) -- Yuri Mikhailovich Lotman -- Colección Fundamentos -- 58, 2a_ ed, Madrid, Spain, 1982 -- isbn13 9788470900389 -- 4480b03d66ff355f311ea74b62df49a6 -- Anna.pdf',
  updated_at    = now()
where id = 'lotman-estructura-texto-artistico-1980';

update books set
  source_format = 'pdf_text',
  source_path   = 'pipeline/corpus/Catálogo de textos marginados novohispanos _ Inquisición, -- Archivo General de la Nación (México); realizado por María -- 1_ ed_, México, D_F, -- 9789681206963 -- cacb6717b9cbc386bd096a9e824bb840 -- Anna’s Archive.pdf',
  updated_at    = now()
where id = 'mendez-catalogo-textos-marginados-1992';

update books set
  source_format = 'pdf_text',
  source_path   = 'pipeline/corpus/El laberinto de la soledad, Postdata, Vuelta a El laberinto -- Octavio Paz -- Colección popular (Fondo de Cultura Económica (Mexico)), 5th -- Fondo de -- 9786071633606 -- 0d5ae97792960cf2654326f512e138f4 -- Anna’s Archive.pdf',
  updated_at    = now()
where id = 'paz-laberinto-soledad-1999';

update books set
  source_format = 'pdf_text',
  source_path   = 'pipeline/corpus/Cuentos Españoles De Colorado Y Nuevo México =_ Spanish Folk -- Rael, Juan Bautista_ -- 2d ed_, rev_, Santa Fe, New Mexico, 1977 -- Santa Fe_ Museum -- 9780890130933 -- 4352bea88e457328370a1b7fa8adc57c -- Anna’s Archive.pdf',
  updated_at    = now()
where id = 'rael-cuentos-espanoles-1977';

update books set
  source_format = 'pdf_text',
  source_path   = 'pipeline/corpus/Women%27s_Tales_from_the_New_Mexico_WPA_La_Diabla_a_..._----_(PART_I).pdf',
  notes_internal = coalesce(notes_internal || ' | ', '') || 'filename says PART_I — likely incomplete',
  updated_at    = now()
where id = 'rebolledo-marquez-womens-tales-wpa-2000';

update books set
  source_format = 'pdf_text',
  source_path   = 'pipeline/corpus/RIVERA GARZA CRISTINA. Los muertos indociles.pdf',
  updated_at    = now()
where id = 'rivera-garza-muertos-indociles-2013';

update books set
  source_format = 'pdf_text',
  source_path   = 'pipeline/corpus/Hablando De Brujas Y La Gente De Antes_ Poemas Del Río Chama -- por Jim Sagel; introduction by John Nichols -- Austin, Tex, Texas, 1981 -- Austin, -- 9780916908027 -- 01952a1d38588e8dc6a20a5044187476 -- Anna’s Arc.pdf',
  updated_at    = now()
where id = 'sagel-hablando-de-brujas-1981';

update books set
  source_format = 'pdf_text',
  source_path   = 'pipeline/corpus/Indan given.pdf',
  notes_internal = coalesce(notes_internal || ' | ', '') || 'chapter 1 of 3 files | chapter 2 of 3 files | chapter 3 of 3 files | Several files for this title: Indan given.pdf; Indian given 2.pdf; Indian given 3.pdf',
  updated_at    = now()
where id = 'saldana-portillo-indian-given-2016';

update books set
  source_format = 'pdf_text',
  source_path   = 'pipeline/corpus/The corn woman _ stories and legends of the Hispanic -- retold by Angel Vigil; translated by Jennifer Audrey Lowell -- Bloomsbury USA, Englewood, -- 9780313069895 -- c92fca77f069c30392a6383e68e1bf56 -- Anna’s Archi.pdf',
  updated_at    = now()
where id = 'vigil-corn-woman-1994';

update books set
  source_format = 'pdf_ocr',
  source_path   = 'pipeline/corpus/Moths-The_Las-palomillas-2.pdf',
  notes_internal = coalesce(notes_internal || ' | ', '') || '13pp — excerpt',
  updated_at    = now()
where id = 'viramontes-the-moths';

commit;
