-- Scriptorium — book seed
--
-- Transcribed from Listas_de_examenes_the reader_Octubre_2026.docx on 8 September 2026.
-- Generated, not hand-typed. Re-runnable: every statement is an upsert.
--
-- TRANSCRIPTION RULES
--
--   Gaps are left null. Around twenty entries in the list carry no publisher,
--   place or year; those columns stay empty so that incompleteBooks() surfaces
--   them and she resolves them deliberately. Nothing is inferred.
--
--   Two known errors are corrected, each flagged in notes_internal on its row:
--   "Soler, Ana Laura" -> Ann Laura Stoler, and "Ebrigh, Malcom" -> Malcolm
--   Ebright. Her own query on the Edmundo Delgado entry is preserved as written.
--
--   Names printed first-name-first are inverted, because Chicago bibliography
--   form and lib/citation.ts both expect "Last, First".
--
--   Four list entries name two works apiece and become two rows: Rulfo,
--   Corky Gonzalez with La Chrisx, Francisco Jimenez, and the filmography.
--   85 rows from 80 bullets.
--
--   IDs ARE PERMANENT. They are the primary key, notes and chunks reference
--   them, and they will appear in URLs. Change them now or not at all.

begin;
insert into books (id, title, subtitle, author, translator, editor,
                   publisher, place, year, edition, language, notes_internal)
values
  ('adorno-polemics-possession-2007', 'The Polemics of Possession in Spanish American Narrative', null, 'Adorno, Rolena',
   null, null, 'Yale University Press', null,
   2007, null, 'en', null),
  ('anzaldua-borderlands-1987', 'Borderlands / La Frontera', 'The New Mestiza', 'Anzaldúa, Gloria',
   null, null, 'Aunt Lute Books', null,
   1987, null, 'en,es', null),
  ('castillo-massacre-dreamers-1994', 'Massacre of the Dreamers', 'Essays on Xicanisma', 'Castillo, Ana',
   null, null, 'University of New Mexico', null,
   1994, null, 'en', null),
  ('sanjek-fieldnotes-1990', 'Fieldnotes', null, 'Sanjek, Roger',
   null, null, 'Cornell University Press', null,
   1990, null, 'en', null),
  ('bettelheim-psicoanalisis-cuentos-1977', 'Psicoanálisis de los cuentos de hadas', null, 'Bettelheim, Bruno',
   'Furió, Silvia', null, 'Crítica', null,
   1977, null, 'es', null),
  ('aristoteles-poetica-1974', 'Poética', null, 'Aristóteles',
   null, 'García Yebra, Valentín', 'Gredos', null,
   1974, 'Edición trilingüe', 'es', null),
  ('pimentel-relato-perspectiva-1998', 'Relato en perspectiva', 'Estudio de teoría narrativa', 'Pimentel, Luz Aurora',
   null, null, 'UNAM / Siglo XXI', null,
   1998, null, 'es', null),
  ('gomez-barris-extractive-zone-2017', 'The Extractive Zone', 'Social Ecologies and Decolonial Perspectives', 'Gómez-Barris, Macarena',
   null, null, 'Duke University Press', null,
   2017, null, 'en', null),
  ('gonzales-red-medicine-2012', 'Red Medicine', 'Traditional Indigenous Rites of Birthing and Healing', 'Gonzales, Patrisia',
   null, null, 'University of Arizona Press', null,
   2012, null, 'en', null),
  ('gordon-ghostly-matters-1997', 'Ghostly Matters', 'Haunting and the Sociological Imagination', 'Gordon, Avery F.',
   null, null, 'University of Minnesota Press', null,
   1997, null, 'en', null),
  ('jauregui-espectros-conjuras-2020', 'Espectros y conjuras', 'Asedios a la cuestión colonial', 'Jáuregui, Carlos A.',
   null, null, 'Iberoamericana / Vervuert', null,
   2020, null, 'es', null),
  ('leon-lloronas-children-2004', 'La Llorona''s Children', 'Religion, Life, and Death in the U.S.–Mexican Borderlands', 'León, Luis D.',
   null, null, 'University of California Press', null,
   2004, null, 'en', null),
  ('taylor-archive-repertoire-2003', 'The Archive and the Repertoire', 'Performing Cultural Memory in the Americas', 'Taylor, Diana',
   null, null, 'Duke University Press', null,
   2003, null, 'en', null),
  ('stoler-along-archival-grain-2009', 'Along the Archival Grain', 'Epistemic Anxieties and Colonial Common Sense', 'Stoler, Ann Laura',
   null, null, 'Princeton University Press', null,
   2009, null, 'en', 'List reads "Soler, Ana Laura"; corrected to Ann Laura Stoler at seed. Publisher expanded from "Princeton".'),
  ('derrida-mal-de-archivo-1995', 'Mal de archivo', 'Una impresión freudiana', 'Derrida, Jacques',
   null, null, null, null,
   1995, null, 'es', 'List gives surname only and no publisher.'),
  ('fong-ethnic-studies-research-2008', 'Ethnic Studies Research', 'Approaches and Perspectives', 'Fong, Timothy P.',
   null, null, 'AltaMira Press / Bloomsbury', null,
   2008, null, 'en', null),
  ('gerhard-frontera-norte-1996', 'La frontera norte de la Nueva España', null, 'Gerhard, Peter',
   null, null, 'Universidad Nacional Autónoma de México', 'México',
   1996, null, 'es', null),
  ('lacan-escritos-1955', 'Escritos', null, 'Lacan, Jacques',
   null, null, null, null,
   1955, null, 'es', 'List specifies two essays: "La carta robada" and "Lituraterre". No publisher given.'),
  ('lotman-estructura-texto-artistico-1980', 'Estructura del texto artístico', null, 'Lotman, Yuri M.',
   null, null, 'Istmo', 'Madrid',
   1980, null, 'es', null),
  ('delgado-youre-not-indian', 'You''re not Indian, You''re Mexican', null, 'Delgado, Vivian',
   null, null, null, null,
   null, null, 'en', 'No publisher, place or year in the list.'),
  ('segato-critica-colonialidad-2021', 'La crítica de la colonialidad en ocho ensayos', 'Y una antropología por demanda', 'Segato, Rita Laura',
   null, null, 'Prometeo Libros / Ariel', null,
   2021, null, 'es', null),
  ('taussig-shamanism-colonialism-1987', 'Shamanism, Colonialism, and the Wild Man', 'A Study in Terror and Healing', 'Taussig, Michael',
   null, null, 'University of Chicago Press', null,
   1987, null, 'en', null),
  ('freud-malestar-cultura', 'El malestar en la cultura', null, 'Freud, Sigmund',
   null, null, null, null,
   null, null, 'es', 'List gives surname and title only.'),
  ('rama-transculturacion-narrativa-1982', 'Transculturación narrativa en América Latina', null, 'Rama, Ángel',
   null, null, null, null,
   1982, null, 'es', 'No publisher in the list.'),
  ('saldana-portillo-indian-given-2016', 'Indian Given', 'Racial Geographies across Mexico and the United States', 'Saldaña Portillo, María Josefina',
   null, null, 'New York University Press', null,
   2016, null, 'en', 'Publisher expanded from "NYU".'),
  ('anaya-cuentos-hispanic-southwest-1980', 'Cuentos', 'Tales from the Hispanic Southwest', 'Anaya, Rudolfo, y José Griego y Maestas',
   null, null, 'Museum of New Mexico Press', null,
   1980, null, 'en,es', null),
  ('cobos-dictionary-nm-spanish-2003', 'A Dictionary of New Mexico and Southern Colorado Spanish', null, 'Cobos, Rubén',
   null, null, 'Museum of New Mexico Press', null,
   2003, '2.ª ed.', 'en,es', null),
  ('delgado-witch-stories-new-mexico-1994', 'Witch Stories of New Mexico / Brujas de Nuevo México', null, 'Delgado, Edmundo',
   null, null, 'Sunstone Press', null,
   1994, null, 'en,es', 'Her own query on the entry: "[?] confirmar editorial". Publisher unconfirmed.'),
  ('espinosa-cuentos-de-cuanto-hay-1998', 'Cuentos de cuanto hay / Tales from Spanish New Mexico', null, null,
   'Hayes, Joe', 'Espinosa, J. Manuel', 'University of New Mexico Press', null,
   1998, null, 'en,es', 'Espinosa is recopilador; Joe Hayes edited and translated. Illustrations by William Rotsaert.'),
  ('flores-masera-relatos-inquisicion-2010', 'Relatos populares de la Inquisición novohispana', 'Rito, magia y otras "supersticiones", siglos XVII–XVIII', null,
   null, 'Flores, Enrique, y Mariana Masera', 'Consejo Superior de Investigaciones Científicas / Universidad Nacional Autónoma de México', 'Madrid',
   2010, null, 'es', null),
  ('garcia-brujas-bultos-brasas-1999', 'Brujas, bultos, y brasas', 'Tales of Witchcraft and the Supernatural in the Pecos Valley', null,
   null, 'García, Nasario', 'Western Edge Press', 'Santa Fe',
   1999, null, 'en,es', null),
  ('garcia-brujerias-2007', 'Brujerías', 'Stories of Witchcraft and the Supernatural in the American Southwest and Beyond', null,
   null, 'García, Nasario', 'Texas Tech University Press', null,
   2007, null, 'en,es', 'Printed with an em-dash repeat for the author, being the second García entry.'),
  ('rebolledo-marquez-womens-tales-wpa-2000', 'Women''s Tales from the New Mexico WPA', 'La diabla a pie', null,
   null, 'Rebolledo, Tey Diana, y María Teresa Márquez', 'Arte Público Press', null,
   2000, null, 'en,es', null),
  ('garcez-american-indian-ghost-stories-2003', 'American Indian Ghost Stories of the West', null, 'Garcez, Antonio R.',
   null, null, 'Red Rabbit Press', null,
   2003, null, 'en', null),
  ('kraul-beatty-weeping-woman-1988', 'The Weeping Woman', 'Encounters with La Llorona', 'Kraul, Edward Garcia, y Judith Beatty',
   null, null, 'Word Process', 'Santa Fe',
   1988, null, 'en', null),
  ('pijoan-spanish-american-folktales-1990', 'Spanish-American Folktales', 'The Practical Wisdom of Spanish-Americans in 28 Eloquent and Simple Stories', 'Pijoan de Van Etten, Teresa',
   null, null, 'August House', null,
   1990, null, 'en', null),
  ('powers-singing-for-my-echo-1987', 'Singing for My Echo', 'Memories of Gregorita Rodríguez, a Native Healer of Santa Fe', 'Powers, Edith',
   null, null, 'Cota Editions', null,
   1987, null, 'en', null),
  ('rael-cuentos-espanoles-1977', 'Cuentos españoles de Colorado y Nuevo México / Spanish Folk Tales from Colorado and New Mexico', null, null,
   null, 'Rael, Juan B.', 'Museum of New Mexico Press', null,
   1977, '2 vols.', 'en,es', null),
  ('sagel-hablando-de-brujas-1981', 'Hablando de brujas y la gente de antes', 'Poemas del Río Chama', 'Sagel, Jim',
   null, null, 'Place of Herons Press', null,
   1981, null, 'es', 'Introduction by John Nichols.'),
  ('vigil-corn-woman-1994', 'The Corn Woman', 'Stories and Legends of the Hispanic Southwest', null,
   'Lowell, Jennifer Audrey', 'Vigil, Ángel', 'Libraries Unlimited / Bloomsbury', 'Englewood',
   1994, null, 'en,es', null),
  ('cabeza-de-vaca-naufragios-1989', 'Naufragios', null, 'Cabeza de Vaca, Álvar Núñez',
   null, 'Maura, Juan Francisco', 'Cátedra', null,
   1989, null, 'es', null),
  ('hendricks-ebright-witches-abiquiu-2006', 'The Witches of Abiquiu', 'The Governor, the Priest, the Genízaro Indians, and the Devil', 'Hendricks, Rick, y Malcolm Ebright',
   null, null, null, null,
   2006, null, 'en', 'List reads "Ebrigh, Malcom"; corrected to Malcolm Ebright at seed. No publisher given.'),
  ('mendez-catalogo-textos-marginados-1992', 'Catálogo de textos marginados novohispanos', 'Inquisición, siglos XVIII y XIX. Archivo General de la Nación (México)', null,
   null, 'Méndez, María Águeda', 'Archivo General de la Nación / El Colegio de México / Universidad Nacional Autónoma de México', 'México, D.F.',
   1992, null, 'es', null),
  ('villagra-historia-nueva-mexico-2010', 'Historia de la Nueva México', null, 'Villagrá, Gaspar de',
   null, 'Junquera, Mercedes', 'Instituto Franklin / Universidad de Alcalá', null,
   2010, null, 'es', null),
  ('hawk-van-alst-never-whistle-2023', 'Never Whistle at Night', 'An Indigenous Dark Fiction Anthology', null,
   null, 'Hawk, Shane, y Theodore C. Van Alst Jr.', 'Vintage Books', null,
   2023, null, 'en', null),
  ('venegas-don-chipote', 'Las aventuras de Don Chipote o cuando los pericos mamen', null, 'Venegas, Daniel',
   null, null, 'Arte Público Press / SEP', null,
   null, null, 'es', 'No year in the list.'),
  ('revueltas-luto-humano-1943', 'El luto humano', null, 'Revueltas, José',
   null, null, null, null,
   1943, null, 'es', 'No publisher in the list.'),
  ('viramontes-the-moths', 'The Moths and Other Stories', null, 'Viramontes, Helena María',
   null, null, 'Arte Público Press', null,
   null, null, 'en', 'List also gives the Spanish title "Las palomillas de la noche". No year.'),
  ('chavez-loving-pedro-infante-2001', 'Loving Pedro Infante', null, 'Chávez, Denise',
   null, null, 'Farrar, Straus and Giroux', null,
   2001, null, 'en', null),
  ('diaz-postcolonial-love-poem-2020', 'Postcolonial Love Poem', null, 'Díaz, Natalie',
   null, null, 'Graywolf Press', null,
   2020, null, 'en', null),
  ('fajardo-anstine-sabrina-corina-2019', 'Sabrina & Corina', 'Stories', 'Fajardo-Anstine, Kali',
   null, null, 'One World / Random House', null,
   2019, null, 'en', null),
  ('fragoza-eat-the-mouth-2021', 'Eat the Mouth That Feeds You', null, 'Fragoza, Carribean',
   null, null, 'City Lights Publishers', null,
   2021, null, 'en', null),
  ('fuentes-muerte-artemio-cruz', 'La muerte de Artemio Cruz', null, 'Fuentes, Carlos',
   null, null, 'Alfaguara', null,
   null, null, 'es', 'No year in the list.'),
  ('herrera-transmigracion-cuerpos-2013', 'La transmigración de los cuerpos', null, 'Herrera, Yuri',
   null, null, 'Editorial Periférica', null,
   2013, null, 'es', null),
  ('paz-laberinto-soledad-1999', 'El laberinto de la soledad', null, 'Paz, Octavio',
   null, null, 'Fondo de Cultura Económica', null,
   1999, 'Edición conmemorativa, 50 aniversario', 'es', null),
  ('gonzales-yo-soy-joaquin', 'Yo soy Joaquín', null, 'González, Rodolfo "Corky"',
   null, null, null, null,
   null, null, 'es,en', 'Listed as "Corky González", paired with the La Chrisx poem.'),
  ('la-chrisx-loca-raza-cosmica-1978', 'La Loca de la Raza Cósmica', null, 'La Chrisx',
   null, null, null, null,
   1978, null, 'es,en', 'Split from the Corky González entry, which paired the two poems.'),
  ('corpi-poems-1980', 'Poems', null, 'Corpi, Lucha',
   null, null, 'Fuego de Aztlán', null,
   1980, null, 'es,en', null),
  ('rivera-y-no-se-lo-trago-1996', '...y no se lo tragó la tierra / ...And the Earth Did Not Devour Him', null, 'Rivera, Tomás',
   'Vigil-Piñón, Evangelina', null, 'Arte Público Press', null,
   1996, null, 'es,en', 'Original work published 1971.'),
  ('rivera-garza-muertos-indociles-2013', 'Los muertos indóciles', 'Necroescrituras y desapropiación', 'Rivera Garza, Cristina',
   null, null, 'Tusquets Editores', null,
   2013, null, 'es', null),
  ('jimenez-cajas-de-carton-1999', 'Cajas de cartón', null, 'Jiménez, Francisco',
   null, null, null, null,
   1999, null, 'es', 'No publisher in the list.'),
  ('jimenez-senderos-fronterizos-2002', 'Senderos fronterizos', null, 'Jiménez, Francisco',
   null, null, null, null,
   2002, null, 'es', 'Split from the Cajas de cartón entry, which listed both. No publisher.'),
  ('luiselli-ninos-perdidos-2016', 'Los niños perdidos', null, 'Luiselli, Valeria',
   null, null, null, null,
   2016, null, 'es', 'No publisher in the list.'),
  ('campobello-cartucho', 'Cartucho', null, 'Campobello, Nellie',
   null, null, null, null,
   null, null, 'es', 'No publisher or year in the list.'),
  ('rulfo-pedro-paramo', 'Pedro Páramo', null, 'Rulfo, Juan',
   null, null, null, null,
   null, null, 'es', 'No publisher or year in the list. Paired with El llano en llamas.'),
  ('rulfo-llano-en-llamas', 'El llano en llamas', null, 'Rulfo, Juan',
   null, null, null, null,
   null, null, 'es', 'Split from the Pedro Páramo entry, which listed both.'),
  ('azuela-los-de-abajo', 'Los de abajo', null, 'Azuela, Mariano',
   null, null, null, null,
   null, null, 'es', 'Printed first-name-first; inverted at seed. No publisher or year.'),
  ('payno-bandidos-rio-frio', 'Los bandidos del Río Frío', null, 'Payno, Manuel',
   null, null, null, null,
   null, null, 'es', 'List gives surname only. No publisher or year.'),
  ('frias-tomochic', 'Tomochic', null, 'Frías, Heriberto',
   null, null, null, null,
   null, null, 'es', 'Printed first-name-first; inverted at seed. No publisher or year.'),
  ('castillo-the-guardians', 'The Guardians', null, 'Castillo, Ana',
   null, null, null, null,
   null, null, 'en', 'Printed first-name-first; inverted at seed. No publisher or year.'),
  ('vasconcelos-raza-cosmica', 'La raza cósmica', null, 'Vasconcelos, José',
   null, null, null, null,
   null, null, 'es', 'No publisher or year in the list.'),
  ('moraga-xicana-codex', 'A Xicana Codex of Changing Consciousness', 'Writings, 2000–2010', 'Moraga, Cherríe',
   null, null, null, null,
   null, null, 'en', 'No publisher or year in the list.'),
  ('gomez-pena-bitacora-del-cruce-2006', 'Bitácora del cruce', null, 'Gómez-Peña, Guillermo',
   null, null, null, null,
   2006, null, 'es', 'No publisher in the list.'),
  ('ulica-cronicas-diabolicas-1982', 'Crónicas diabólicas, 1916–1926', null, 'Arce, Julio G. ("Jorge Ulica")',
   null, null, null, null,
   1982, null, 'es', 'Listed under the pen name Jorge Ulica. Spanish edition, 1982. No publisher.'),
  ('valdemar-garcia-casa-del-brujo-1984', 'La casa del brujo', null, 'Valdemar García, Itzolin',
   null, null, 'Muchos Charcos', null,
   1984, null, 'es', null),
  ('anzaldua-prietita-ghost-woman-1995', 'Prietita and the Ghost Woman', null, 'Anzaldúa, Gloria',
   null, null, null, null,
   1995, null, 'en,es', 'No publisher in the list.'),
  ('mendez-muertos-tambien-cuentan-1995', 'Los muertos también cuentan', null, 'Méndez, Miguel',
   null, null, null, null,
   1995, null, 'es', 'No publisher in the list.'),
  ('alarcon-from-the-other-side-2002', 'From the Other Side of the Night', null, 'Alarcón, Francisco X.',
   null, null, null, 'Arizona',
   2002, null, 'en,es', 'List gives "Arizona" where a publisher would go; likely University of Arizona Press.'),
  ('grande-traves-cien-montanas-2007', 'A través de cien montañas', null, 'Grande, Reyna',
   null, null, null, null,
   2007, null, 'es', 'No publisher in the list.'),
  ('paredes-with-his-pistol-1958', 'With His Pistol in His Hand', null, 'Paredes, Américo',
   null, null, null, null,
   1958, null, 'en', 'No publisher in the list.'),
  ('anaya-bless-me-ultima', 'Bless Me, Ultima', null, 'Anaya, Rudolfo',
   null, null, null, null,
   null, null, 'en', 'No publisher or year in the list.'),
  ('pineda-nostalgia-no-se-marcha-2024', 'La nostalgia no se marcha como el agua de los ríos', null, 'Pineda, Irma',
   null, null, null, null,
   2024, null, 'es', 'Printed first-name-first; inverted at seed. No publisher.'),
  ('arias-camino-tamazunchale-1975', 'El camino a Tamazunchale', null, 'Arias, Ron',
   null, null, null, null,
   1975, null, 'es', 'Printed first-name-first; inverted at seed. No publisher.'),
  ('lash-of-the-penitentes-1936', 'The Lash of the Penitentes', null, 'Price, Roland, y Harry Revier',
   null, null, null, null,
   1936, null, 'en', 'A film, not a book. Produced by Harry Revier; directed by Roland Price and Harry Revier.'),
  ('melendez-hidden-chicano-cinema-2013', 'Hidden Chicano Cinema', 'Film Dramas in the Borderlands', 'Meléndez, A. Gabriel',
   null, null, 'Rutgers University Press', null,
   2013, null, 'en', 'Listed alongside The Lash of the Penitentes as its companion study.')
on conflict (id) do update set
  title = excluded.title, subtitle = excluded.subtitle, author = excluded.author,
  translator = excluded.translator, editor = excluded.editor,
  publisher = excluded.publisher, place = excluded.place, year = excluded.year,
  edition = excluded.edition, language = excluded.language,
  notes_internal = excluded.notes_internal, updated_at = now();

-- List membership. Sort follows the order printed in the document.
insert into list_items (list_id, book_id, sort)
values
  ('theory', 'adorno-polemics-possession-2007', 1),
  ('theory', 'anzaldua-borderlands-1987', 2),
  ('theory', 'castillo-massacre-dreamers-1994', 3),
  ('theory', 'sanjek-fieldnotes-1990', 4),
  ('theory', 'bettelheim-psicoanalisis-cuentos-1977', 5),
  ('theory', 'aristoteles-poetica-1974', 6),
  ('theory', 'pimentel-relato-perspectiva-1998', 7),
  ('theory', 'gomez-barris-extractive-zone-2017', 8),
  ('theory', 'gonzales-red-medicine-2012', 9),
  ('theory', 'gordon-ghostly-matters-1997', 10),
  ('theory', 'jauregui-espectros-conjuras-2020', 11),
  ('theory', 'leon-lloronas-children-2004', 12),
  ('theory', 'taylor-archive-repertoire-2003', 13),
  ('theory', 'stoler-along-archival-grain-2009', 14),
  ('theory', 'derrida-mal-de-archivo-1995', 15),
  ('theory', 'fong-ethnic-studies-research-2008', 16),
  ('theory', 'gerhard-frontera-norte-1996', 17),
  ('theory', 'lacan-escritos-1955', 18),
  ('theory', 'lotman-estructura-texto-artistico-1980', 19),
  ('theory', 'delgado-youre-not-indian', 20),
  ('theory', 'segato-critica-colonialidad-2021', 21),
  ('theory', 'taussig-shamanism-colonialism-1987', 22),
  ('theory', 'freud-malestar-cultura', 23),
  ('theory', 'rama-transculturacion-narrativa-1982', 24),
  ('theory', 'saldana-portillo-indian-given-2016', 25),
  ('dissertation', 'anaya-cuentos-hispanic-southwest-1980', 1),
  ('dissertation', 'cobos-dictionary-nm-spanish-2003', 2),
  ('dissertation', 'delgado-witch-stories-new-mexico-1994', 3),
  ('dissertation', 'espinosa-cuentos-de-cuanto-hay-1998', 4),
  ('dissertation', 'flores-masera-relatos-inquisicion-2010', 5),
  ('dissertation', 'garcia-brujas-bultos-brasas-1999', 6),
  ('dissertation', 'garcia-brujerias-2007', 7),
  ('dissertation', 'rebolledo-marquez-womens-tales-wpa-2000', 8),
  ('dissertation', 'garcez-american-indian-ghost-stories-2003', 9),
  ('dissertation', 'kraul-beatty-weeping-woman-1988', 10),
  ('dissertation', 'pijoan-spanish-american-folktales-1990', 11),
  ('dissertation', 'powers-singing-for-my-echo-1987', 12),
  ('dissertation', 'rael-cuentos-espanoles-1977', 13),
  ('dissertation', 'sagel-hablando-de-brujas-1981', 14),
  ('dissertation', 'vigil-corn-woman-1994', 15),
  ('dissertation', 'cabeza-de-vaca-naufragios-1989', 16),
  ('dissertation', 'hendricks-ebright-witches-abiquiu-2006', 17),
  ('dissertation', 'mendez-catalogo-textos-marginados-1992', 18),
  ('dissertation', 'villagra-historia-nueva-mexico-2010', 19),
  ('dissertation', 'hawk-van-alst-never-whistle-2023', 20),
  ('teaching', 'venegas-don-chipote', 1),
  ('teaching', 'revueltas-luto-humano-1943', 2),
  ('teaching', 'viramontes-the-moths', 3),
  ('teaching', 'chavez-loving-pedro-infante-2001', 4),
  ('teaching', 'diaz-postcolonial-love-poem-2020', 5),
  ('teaching', 'fajardo-anstine-sabrina-corina-2019', 6),
  ('teaching', 'fragoza-eat-the-mouth-2021', 7),
  ('teaching', 'fuentes-muerte-artemio-cruz', 8),
  ('teaching', 'herrera-transmigracion-cuerpos-2013', 9),
  ('teaching', 'paz-laberinto-soledad-1999', 10),
  ('teaching', 'gonzales-yo-soy-joaquin', 11),
  ('teaching', 'la-chrisx-loca-raza-cosmica-1978', 12),
  ('teaching', 'corpi-poems-1980', 13),
  ('teaching', 'rivera-y-no-se-lo-trago-1996', 14),
  ('teaching', 'rivera-garza-muertos-indociles-2013', 15),
  ('teaching', 'jimenez-cajas-de-carton-1999', 16),
  ('teaching', 'jimenez-senderos-fronterizos-2002', 17),
  ('teaching', 'luiselli-ninos-perdidos-2016', 18),
  ('teaching', 'campobello-cartucho', 19),
  ('teaching', 'rulfo-pedro-paramo', 20),
  ('teaching', 'rulfo-llano-en-llamas', 21),
  ('teaching', 'azuela-los-de-abajo', 22),
  ('teaching', 'payno-bandidos-rio-frio', 23),
  ('teaching', 'frias-tomochic', 24),
  ('teaching', 'castillo-the-guardians', 25),
  ('teaching', 'vasconcelos-raza-cosmica', 26),
  ('teaching', 'moraga-xicana-codex', 27),
  ('teaching', 'gomez-pena-bitacora-del-cruce-2006', 28),
  ('teaching', 'ulica-cronicas-diabolicas-1982', 29),
  ('teaching', 'valdemar-garcia-casa-del-brujo-1984', 30),
  ('teaching', 'anzaldua-prietita-ghost-woman-1995', 31),
  ('teaching', 'mendez-muertos-tambien-cuentan-1995', 32),
  ('teaching', 'alarcon-from-the-other-side-2002', 33),
  ('teaching', 'grande-traves-cien-montanas-2007', 34),
  ('teaching', 'paredes-with-his-pistol-1958', 35),
  ('teaching', 'anaya-bless-me-ultima', 36),
  ('teaching', 'pineda-nostalgia-no-se-marcha-2024', 37),
  ('teaching', 'arias-camino-tamazunchale-1975', 38),
  ('filmografia', 'lash-of-the-penitentes-1936', 1),
  ('filmografia', 'melendez-hidden-chicano-cinema-2013', 2)
on conflict (list_id, book_id) do update set sort = excluded.sort;

commit;
